language: objective-c
podfile: Example/Podfile
osx_image: xcode8.0
rvm:  2.2.3
xcode_project: Example/HISwiftExtensions.xcworkspace # path to your xcodeproj folder
xcode_scheme: HISwiftExtensions-Example
before_install:
 - gem install cocoapods
 - pod install --project-directory=Example
only:
- master
script:
- pod lib lint
after_success:
- chmod +x ./Resources/scripts/docs.sh
- ./Resources/scripts/docs.sh
